### ISSUE TITLE
Improve code style

### ISSUE THREAD

**Issue by sandord** [sharparchitecture/Sharp-Architecture#81] opened 2012-10-30 21:51 UTC
I'd like to propose a few ways to improve the code style a bit (which currently isn't bad by any means).

Please let me know if you disagree with any of these or have anything to add.
1. use `var` only when absolutely necessary
2. apply white space before scope creating statements (e.g. statements with a body), unless the preceding line is a curly bracket. For example:
   
   ```
   public void Foo()
   {
       int count = 10;
   
       for (int i = 0; i < count; i++)
       {
       }
    }
   ```
3. use one class/interface/struct per file only (applies to public and internal types only)
4. split `using` statements by group (first namespace level only). For example:
   
   ```
   using System.ComponentModel.DataAnnotations;
   using System.Linq;
   
   using Microsoft.Practices.ServiceLocation;
   ```
5. refrain from using regions other than those generated by ReSharper (a separate region for fields, constructors, properties, public methods, private methods)

**Comment by shatl** [comment] 2015-04-13 22:06
Looks like StyleCop is not actively developed now... At lease R# 9 support is still in beta.
Should we close this issue or update R# code formatting options?

**Comment by alecwhittington** [comment] 2015-04-13 23:58
@shatl No one is really sure about the future of StyleCop right now. There seem to be some renewed interest in it from the community, but what will become of it is anyone's guess. It's truly a shame, it has been invaluable to me over the years. I personally would leave this open as the issue is still valid.

**Comment by HowardvanRooijen** [comment] 2015-04-14 06:01
A few people have contacted me about supporting the product, but I have a feeling that the codebase as is, is quite complex to support & extend. One of the more interesting projects out there has started to port the rules and quickfixes over to the Roslyn platform. It looks really good, the code is lean & was to grok. I'd suggest supporting that if you want to use StyleCop in the future.

Sent from my Windows Phone
________________________________

**Comment by shatl** [comment] 2015-05-15 20:15
Regarding the code style, what is the purpose of using `this.` when calling methods on objects? 
I'd rather get rid of using `this` in favour of prefixing fields with underscore.

**Comment by alecwhittington** [comment] 2015-05-15 20:20
'this.' and '_' serve the same exact purpose - it comes down to being an argument about 'religion' so to speak. It is purely a personal preference and either can easily be setup up in R#

**Comment by HowardvanRooijen** [comment] 2015-05-15 21:04
Well, to be more specific, "this" is a qualifier, whereas "_" is a coding standard.

My perspective has always been to enforce a coding standard with a tool (like stylecop) because otherwise you are just relying on peoples habits, which are more often than not, variable & inconsistent!

The other reason I've always liked stylecop is that the .net framework team & windiv had years of arguments on their mailing lists to agree on those conventions... There's a lot of wisdom and real world experience encapsulated in those rules, I'm not sure I'm more qualified to argue... It's really just personal preference. As you say, ReSharper makes cleaning up code into any coding standard so easy!

Do whatever works & is consistent! The point of a coding standard is that you shouldn't be able to tell which member of your team wrote any single line of code...
________________________________

**Comment by shatl** [comment] 2018-07-04 18:39
Added shared ReSharper settings

**Closed by shatl** 2018-07-04 18:39 UTC
